vinszent/gnome-twitch

- README.md
Just published a package of ubuntu-twitch on the Ubuntu software site GetDeb.net.
It is available for Ubuntu 15.04.
> Add GetDeb for Ubuntu package

- po/POTFILES.in
Autoreconf fails if the file containing translations is missing.
Error:
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.
data/ui/gt-player-header-bar.ui
> Add missing file to POTFILES

- data/packages/pacman/gnome-twitch-git/PKGBUILD
- data/packages/pacman/gnome-twitch/PKGBUILD
Some programs like pacaur + makepkg do not remove the build directory prior to building anew. Fix this in the PKGBUILD files. Additionally move meson options to build() function.
> PKGBUILD: Remove build directory and early meson options.

- src/gt-win.c
Currently most keys on the keyboard pauses the video. I believe It was the author's intention
that only the spacebar paused the video.
> Let only the spacebar pause the video.

- src/gt-player-clutter.c
Hi,
I created a small patch to prevent the screensaver from starting when watching a stream. Totem and Epiphany work in a similar way.
> Inhibit screensaver during playback.

- data/com.gnome-twitch.app.desktop
According to the desktop file specification, a trailing semicolon after lists of values is optional, yet some verification tools will warn about it if it is missing.
I also added a "Keywords" entry, since lintian (a tool used in Debian to automatically check packages) recommends to add this.
> Fixed desktop file

- src/main.c
There is a spelling error in src/main.c.
This commit fixes that.
> Fixed spelling error: unkown -> unknown

- src/gt-app.c
Adwaita has a dark variant that works well for Totem. This commit applies it to Gnome Twitch. I think that it would be fine for the chat too (see YouTube Gaming).
> Prefer dark theme variant, if applicable.

- print_git_version.sh
- src/gt-enums.c
- src/gt-win.c
This removes two build warnings when using gcc 5 and a shell error if /bin/sh is not a bash.
> Fix a few build warnings

- README.md
Since gnome-twitch has made it into Debian some time ago (I maintain the package there), I added it to the list of distros in the Readme.
While we're at it: It might be a little early for this "reminder", but consider that the version of gnome-twitch in Debian testing at the time of the freeze will be the version that goes into the next stable. Also, new versions need a few days to transition from unstable (where they are uploaded) to testing (if everything works smoothly, i.e. no dependency issues or anything). According to https://wiki.debian.org/DebianStretch the transition freeze starts on 2016-09-05, so the packaging work should be finished in summer 2016.
The reason I'm saying this is because the stable release will be around for a long time and people using it will report their …
> Added Debian to the list of distros containing gnome-twitch.

- src/gt-player-clutter.c
This was omitted in pull request #73. I also found a bug that occurred when having multiple windows, but it seems related to GTK+. See [this](https://mail.gnome.org/archives/clutter-list/2016-February/msg00006.html) thread.
> Ensure that the timeout source is removed.

- src/main.c
With this commit, GNOME Twitch can be compiled without any warnings.
> Check return value of gtk_clutter_init().

- data/ui/app-menu.ui
- src/gt-browse-header-bar.c
- src/gt-browse-header-bar.h
- src/gt-channels-view.c
- src/gt-channels-view.h
- src/gt-favourites-view.c
- src/gt-favourites-view.h
- src/gt-games-view.c
- src/gt-games-view.h
- src/gt-win.c
This patch allows to search in the channels, favourites, or games views,
just by starting to type. This should fix issue #8. The search bar can be
toggled by pressing Ctrl+F or dismissed by pressing Escape.
Pressing Escape in the player view exits fullscreen or closes the player
and returns to the browse views if windowed. The F key can be used to
toggle fullscreen.
Ctrl+Q immediately quits the application.
> Extend keyboard support for search and fullscreen

- meson_post_install.sh
This commit addresses issue #86. If the script is run outside of meson, it will still work, but will assume `/usr` as the install prefix.
> Use prefix from meson in post-install script.

- data/ui/gt-channels-container-child.ui
- data/ui/gt-games-container-child.ui
This happened today:
The first commit fixes this issue for the channels container. The second one improves the current limits of the games container.
> Apply limits to the labels of the container children

- src/gt-app.c
- src/gt-channel.c
- src/gt-twitch.c
- src/gt-twitch.h
- src/utils.c
- src/utils.h
Banners and box art change rarely. By caching them to disk, the start-up time of GNOME Twitch can be substantially improved. When I tested this, with 10 favorite channels and a hot cache, the amount of data transferred on start-up dropped from about 12 MB to just over 2 MB.
The last commit as a bit of a gimmick, but what it means is that cached images will be considered fresh for 7 to 14 days. I think that this is a reasonable lifespan.
> Cache channel offline banners and game box art

- src/gt-app.c
- src/gt-player-clutter.c
First commit was originally part of the `refresh_favourites` branch. Second commit fixes a bug introduced by commit `e99dcde` for issue #115.
> Minor fixes

- LICENSE
There were some words missing in the copyright statement, probably lost during copy&paste. Also I updated the year.
> Add missing words to copyright statement

- README.md
- po/meson.build
With meson 0.32, gnome-twitch fails to build:
```
Meson encountered an error in file po/meson.build, line 3, column 0:
Gettext() function has been moved to module i18n. Import it and use i18n.gettext() instead
```
This PR fixes this.
(BTW I have no idea why Github shows line 46 in the README as changed, it's exactly the same.)
> New meson behavior

- po/sr.po
Updated the Serbian translation. Sorry for waiting a bit, master is a bit PITA to build and install under Fedora 24. Had do temporarily install meson 0.33 from Rawhide because 24 ships with 0.31. Also, `ninja install` is `ninja-build install` in Fedora.
> Updated Serbian translation.

- src/gt-twitch.c
Compiling with -Werror=format-security fails because a printf-like function was used in an unsafe way.
Format strings for functions like this should be string literals, to avoid injection of
format specifiers, which can lead to undefined behavior if they are not filled in with arguments.
If one wants to pass a normal string to one of those functions without formatting, the format string
"%s" should be used, with the desired string passed as an argument for it.
See also:
https://stackoverflow.com/questions/17260409/fprintf-error-format-not-a-string-literal-and-no-format-arguments-werror-for
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
> Replace unsafe format string by safe alternative

- data/com.vinszent.GnomeTwitch.desktop.in
According to https://specifications.freedesktop.org/desktop-entry-spec/1.0/apc.html the Encoding key is deprecated.
All desktop files are now required to be encoded in UTF-8.
> Remove deprecated Encoding key in desktop file

- data/com.vinszent.GnomeTwitch.appdata.xml.in
- data/meson.build
This is used by gnome-software and potentially other stores.
This is basically a revival of #81 which needed rebasing and fixes anyway.
> Add appdata file

- src/gt-chat.c
Since it's a verb, it is spelled "log in".
Otherwise it becomes a noun.
> Fix spelling of log in

- data/com.vinszent.GnomeTwitch.appdata.xml.in
- data/com.vinszent.GnomeTwitch.gschema.xml
- src/gt-app.c
- src/gt-game.c
- src/gt-player.c
- src/gt-twitch-login-dlg.c
- src/gt-win.c
See https://developer.gnome.org/hig/stable/typography.html. Plus some improvements to translatable strings. Probably post-0.4.1 material. :)
> Use Unicode in translatable strings

- include/gnome-twitch/gt-player-backend.h
- src/gt-app.c
- src/gt-resource-downloader.c
- src/meson.build
I did a bunch of things in order to make it possible to write player-backends in other languages than C and make full-fledged use of GObject Introspection.
> Make gnome-twitch ready for gobject-introspection

- data/meson.build
The path where AppStream metadata is stored has changed. The old path is still supported as a legacy path, but using the new path is advised. See section 2.1.2 in https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
> Adjust to new AppStream metadata path

- README.md
Hello.
I have imported gnome-twitch into the OpenBSD package repository. See: https://marc.info/?l=openbsd-ports-cvs&m=150806716929103&w=2
I have added a link to the gnome-twitch package on the OpenBSD package tracker to README.md. It will propagate in the next few hours.
Thanks!
> Add link to OpenBSD package.

- player-backends/player-backend-mpv-opengl/gt-player-backend-mpv-opengl.c
Currently the video doesn't fill the display area.
> Support hi-dpi monitors in mpv backend

- player-backends/player-backend-mpv-opengl/gt-player-backend-mpv-opengl.c
I just added the automatic detection by mpv and the CPU usage went down from 90% to like 10%. The mpv documentation says that it will try vaapi, vdpau and then fall back to software rendering.
> enable mpv's automatic hardware decoder detection

- src/gt-twitch.c
Apparently Twitch now requires SSL for (some?) APIs. The other problem is that usher.twitch.tv has a broken SSL certificate, because the domain listed is usher.ttvnw.net. That URL seems to work.
Should fix #356
> Use new Twitch API URL over SSL

- README.md
Package was promoted from AUR to Community repo; I've updated the link for it.
> Update gnome-twitch package link for Arch Linux
