po/meson.build
po/sr.po

Added Serbian translation.

---

data/gnome-twitch.gschema.xml
data/ui/gt-settings-dlg.ui
src/gt-app.c
src/gt-settings-dlg.c
src/gt-win.c

The first commit fixes a minor bug I encountered. The second commit implements what was discussed in pull request #55.

Make the theme variant configurable.

---

src/gt-win.c

This fixes a small inconsistency I introduced. Thanks for taking the time to review my patches.

Group global variable declarations.

---

src/gt-player-clutter.c

This commit addresses issue #67. However, it is not limited to fullscreen mode.

Automatically hide the mouse cursor.

---

po/meson.build
po/pt_PT.po

Adding Portuguese (European) translation

Add Portuguese translation

---

src/gt-twitch-login-dlg.c

The input id is not login but username.

Fix twitch login.

---

po/hu.po
po/meson.build

The translation is updated according to the new code base.

Hungarian translation for the 0.2.0 release.

---

po/hu.po

Gave it a day and revised a string.

fix po/hu.po mistranslation

---

src/gt-channel.c
src/gt-game.c

Fix memory leaks

---

po/fr.po

Add 0.3.0 translation
Some fix

Update french for 0.3.0 release

---

po/LINGUAS
po/nl.po

This is the translation file for the dutch translation

PO file for Dutch translation

---

po/nl.po

Fixed a small error in the translation

Fix a error in Dutch translation

---

src/gt-irc.c

Fix spelling error recive -> receive

---

CONTRIBUTING.md
po/LINGUAS
po/cs.po
po/meson.build

Czech translation for the 0.3.0 version.

Add Czech Translation

---

data/com.vinszent.GnomeTwitch.gschema.xml
src/gt-irc.c
src/gt-twitch.c

Just some minor typo's I spoted.

minor typos

---

data/meson.build

The build directory is undefined so the relative path isn't correct.

Fix translating desktop file

---

data/meson.build
include/meson.build
meson.build
meson_options.txt
meson_post_install.sh
po/meson.build
src/config.h.in
src/meson.build
subprojects/player-backend-gstreamer-cairo/meson.build
subprojects/player-backend-gstreamer-clutter/meson.build
subprojects/player-backend-gstreamer-opengl/meson.build
subprojects/player-backend-mpv-opengl/meson.build

Just a few improvements to improve correctness, clean up repetition, and make use of built-in functionality of meson.

Improve build system

---

src/gt-app.c

Fix typo in gt-app.c

---

po/hu.po

Update HU localization

---

player-backends/player-backend-mpv-opengl/gt-player-backend-mpv-opengl.c

Fix MPV backend (building on new GLib, working with new MPV)
